INSERT INTO City_states VALUES('New York','New York');
INSERT INTO City_states VALUES('Los Angeles','California');
INSERT INTO City_states VALUES('Chicago','Illinois');
INSERT INTO City_states VALUES('Houston','Texas');
INSERT INTO City_states VALUES('Philadelphia','Pennsylvania');
INSERT INTO City_states VALUES('Phoenix','Arizona');
INSERT INTO City_states VALUES('San Antonio','Texas');
INSERT INTO City_states VALUES('San Diego','California');
INSERT INTO City_states VALUES('Dallas','Texas');
INSERT INTO City_states VALUES('San Jose','California');
INSERT INTO City_states VALUES('Austin','Texas');
INSERT INTO City_states VALUES('Jacksonville','Florida');
INSERT INTO City_states VALUES('San Francisco','California');
INSERT INTO City_states VALUES('Indianapolis','Indiana');
INSERT INTO City_states VALUES('Columbus','Ohio');
INSERT INTO City_states VALUES('Fort Worth','Texas');
INSERT INTO City_states VALUES('Charlotte','North Carolina');
INSERT INTO City_states VALUES('Seattle','Washington');
INSERT INTO City_states VALUES('Denver','Colorado');
INSERT INTO City_states VALUES('El Paso','Texas');
INSERT INTO City_states VALUES('Atlanta','Georgia');